#!/system/bin/sh

#EXT4 Optimization
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier =0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /data
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /cache

#Network tweaks
echo "0" > /proc/sys/net/ipv4/tcp_timestamps;
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout;
echo "404480" > /proc/sys/net/core/wmem_max;
echo "404480" > /proc/sys/net/core/rmem_max;
echo "256960" > /proc/sys/net/core/rmem_default;
echo "256960" > /proc/sys/net/core/wmem_default;
echo "4096,16384,404480" > /proc/sys/net/ipv4/tcp_wmem;
echo "4096,87380,404480" > /proc/sys/net/ipv4/tcp_rmem;

#Defrag Database
for i in \
`find /data -iname "*.db"`
do \
sqlite3 $i 'VACUUM;'; 
sqlite3 $i 'REINDEX;'; 
done

#RAM Tweaks
# Copyright?2011 Juwe11
#adj and minfree value tweaked for O2X by Squide # 13.8.2011 Updated VM values - Thanks to [Kalis] for help
# 18.8.2011 Added oom_adj values
# 19.9.2011 Updated VM and LMK values
# 12.11.2011 Changed by Einsteinno1


if [ -e /sys/module/lowmemorykiller/parameters/adj ]; then
	echo "0,1,2,7,8,9" > /sys/module/lowmemorykiller/parameters/adj
fi

if [ -e /sys/module/lowmemorykiller/parameters/minfree ]; then
    echo "2560,4096,6144,12288,14336,18432" > /sys/module/lowmemorykiller/parameters/minfree;
fi

if [ -e /proc/sys/vm/swappiness ]; then
	echo "0" > /proc/sys/vm/swappiness
fi

if [ -e /proc/sys/vm/vfs_cache_pressure ]; then
	echo "10" > /proc/sys/vm/vfs_cache_pressure
fi

if [ -e /proc/sys/vm/dirty_expire_centisecs ]; then
	echo "500" > /proc/sys/vm/dirty_expire_centisecs
fi

if [ -e /proc/sys/vm/dirty_writeback_centisecs ]; then
	echo "1000" > /proc/sys/vm/dirty_writeback_centisecs
fi

if [ -e /proc/sys/vm/dirty_ratio ]; then
	echo "30" > /proc/sys/vm/dirty_ratio
fi

if [ -e /proc/sys/vm/dirty_background_ratio ]; then
	echo "3" > /proc/sys/vm/dirty_background_ratio
fi

#SD Tweaks
echo 128 > /sys/devices/virtual/bdi/7:0/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:1/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:2/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:3/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:4/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:5/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:6/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:7/read_ahead_kb
echo 4096 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
echo 4096 > /sys/devices/virtual/bdi/default/read_ahead_kb
echo 97 > /sys/devices/virtual/bdi/179:0/max_ratio
echo 97 > /sys/devices/virtual/bdi/default/max_ratio
echo 4096 > /sys/devices/virtual/bdi/179:0/read_ahead_kb;

#Battery Savings
echo 500 > /proc/sys/vm/dirty_expire_centisecs
echo 1000 > /proc/sys/vm/dirty_writeback_centisecs

#ZRAM
echo 134217728 >  /sys/block/zram0/disksize
/system/xbin/busybox mkswap /dev/block/zram0
/system/xbin/busybox swapon /dev/block/zram0


#Removes LOG
rm /dev/log/main

#Disables normal sleeper
echo NO_NORMALIZED_SLEEPER > /sys/kernel/debug/sched_features

echo "done" > /sdcard/90hundsbuah
