#!/bin/sh

wait=10

mount -t proc -o nodev,noexec,nosuid proc /proc
echo "4 1 1 7" > /proc/sys/kernel/printk
umount /proc

busybox clear

cat <<EOF

Please, select OS to boot:
==========================
 1         - Linux
 2,voldown - Android
 s         - Initrd shell
==========================
You have $wait Seconds to choose...
EOF
echo -n "Please Select (1,2(voldown),s) [1]: "
read -n1 -t $wait inp
echo

case "$inp" in
  2|"")
    echo "Starting Android"
    echo
    /init-android "$@"
    exit 1
    ;;
  s)
    echo "Go to HELL..."
    echo
    /bin/sh -i </dev/console >/dev/console 2>&1
    exit 1
    ;;
  *)
    echo "Starting Linux"
    echo
    . /init-linux "$@"
    exit 1
    ;;
esac
