#!/bin/sh

wait=10

cat <<EOF

Please, select OS to boot:
==========================
 1 - Linux
 2 - Android
==========================
You have $wait Seconds to choose...
EOF
echo -n "Please Select (1,2) [1]: "
read -t $wait inp
echo

case "$inp" in
  2)
    echo "Starting Android"
    echo
    /init-android "$@"
    exit 1
    ;;
  *)
    echo "Starting Linux"
    echo
    . /init-linux "$@"
    exit 1
    ;;
esac
